---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "caddy-injector.fullname" . }}-selfsigner
  labels:
    {{- include "caddy-injector.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "caddy-injector.fullname" . }}-tls
  labels:
    {{- include "caddy-injector.labels" . | nindent 4 }}
spec:
  secretName: {{ include "caddy-injector.fullname" . }}-tls
  dnsNames:
  - {{ include "caddy-injector.fullname" . }}
  - {{ include "caddy-injector.fullname" . }}.{{ .Release.Namespace }}
  - {{ include "caddy-injector.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "caddy-injector.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.domainSuffix }}
  issuerRef:
    name: {{ include "caddy-injector.fullname" . }}-selfsigner