---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "caddy-injector.fullname" . }}-pod-webhook
  labels:
    {{- include "caddy-injector.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "caddy-injector.fullname" . }}-tls
webhooks:
- name: mutate.caddy.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "caddy-injector.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-pod
      port: {{ .Values.service.port }}
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
      {{- if .Values.webhook.matchExpressionsOverride -}}
        {{ toYaml .Values.webhook.matchExpressionsOverride | nindent 6 }}
      {{- else }}
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values: 
          {{- if .Values.webhook.ignoreReleaseNamespace }}
          - {{ .Release.Namespace }}
          {{- end }}
          {{- with .Values.webhook.ignoreNamespaces -}}
            {{ toYaml . | nindent 10 }}
          {{- end }}
      {{- end }}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
