---
apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigner
  namespace: example
spec:
  selfSigned: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      annotations:
        caddy.io/inject: ""
        caddy.io/issuer: selfsigner
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: containous/whoami
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: example
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: whoami
  ports:
   - port: 443
     protocol: TCP
     targetPort: https
